### PR TITLE
Add features from slimevr modified lib

### PR DESCRIPTION
**Pull request by wigwagwent**
**Summary**
When adding the LSM6DSV family to the slimevr firmware we needed a few features that are not present in this library.

This PR fixes/implements the following **bugs/features**

* [ ] Built in Gyro and Accel Tests
* [ ] Temperature ODR and raw
* [ ] Acceleration offset
* [ ] ability to add timestamp to fifo
* [ ] Device reset
* [ ] auto increment and block update exposed
* [ ] Base library updated to the latest
* [ ] Reduced communication amount by not reading sensitivity from imu every time you get the accel/gyro

**Validation**
A slightly modified version using most of these features works in the slimevr firmware but other than that I have not tested every added feature thoroughly.

[SlimeVR Firmware](https://github.com/wigwagwent/LSM6DSV16X/tree/main)

### CODE REVIEW

**Comment by cparata** [comment]
Hello @wigwagwent ,
thanks for the contribution. As you can see, your PR did not pass AStyle, spelling and compilation checks.
For AStyle you can give a look at the guide [here](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Astyle).
For spelling you can give a look at the suggestion [here](https://github.com/stm32duino/LSM6DSV16X/actions/runs/7072647121/job/19285093891).
There is also an issue in the compilation check [here](https://github.com/stm32duino/LSM6DSV16X/actions/runs/7072647121/job/19285093539).
I suggest to fix all these issues before, then I will give a look at the PR.
Thanks again and Best Regards,
Carlo

**Comment by cparata** [comment]
Hello @wigwagwent ,
thanks for the new PR. Regarding the reg files, in STM32duino we decided to patch these files replacing the "stmdev_ctx_t" generic struct with a dedicated struct called "lsm6dsv16x_ctx_t" to avoid compilation errors when several MEMS components are used in the same example. So I prefer to keep the same approach also for this component to avoid misalignments. The rest of APIs seems fine to me. I will try to make a test with this new version in the next days to see if all the examples work properly.
Best Regards,
Carlo

**Comment by wigwagwent** [comment]
I did a search and replace to update all the stmdev_ctx_t to lsm6dsv16x_ctx_t

**Comment by cparata** [comment]
Hello @wigwagwent ,
thanks a lot for your contribution! I have integrated in the main branch your PR with small changes. I will release a new version of the library v2.0.0 with all these changes.
Best Regards,
Carlo

**Pull request closed without merging**
